# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './bulk/bulk_emodulus.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 274)
        icon = QtGui.QIcon.fromTheme("view-statistics")
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_temp = DoubleSpinBoxNan(parent=Dialog)
        self.doubleSpinBox_temp.setWrapping(False)
        self.doubleSpinBox_temp.setReadOnly(False)
        self.doubleSpinBox_temp.setSpecialValueText("")
        self.doubleSpinBox_temp.setMinimum(10.0)
        self.doubleSpinBox_temp.setMaximum(45.0)
        self.doubleSpinBox_temp.setProperty("value", 23.0)
        self.doubleSpinBox_temp.setObjectName("doubleSpinBox_temp")
        self.gridLayout.addWidget(self.doubleSpinBox_temp, 1, 2, 1, 1)
        self.comboBox_medium = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_medium.setObjectName("comboBox_medium")
        self.comboBox_medium.addItem("")
        self.comboBox_medium.addItem("")
        self.comboBox_medium.addItem("")
        self.comboBox_medium.addItem("")
        self.comboBox_medium.addItem("")
        self.gridLayout.addWidget(self.comboBox_medium, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.comboBox_visc_model = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_visc_model.setObjectName("comboBox_visc_model")
        self.comboBox_visc_model.addItem("")
        self.comboBox_visc_model.addItem("")
        self.gridLayout.addWidget(self.comboBox_visc_model, 2, 1, 1, 1)
        self.comboBox_temp = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_temp.setObjectName("comboBox_temp")
        self.comboBox_temp.addItem("")
        self.comboBox_temp.addItem("")
        self.comboBox_temp.addItem("")
        self.gridLayout.addWidget(self.comboBox_temp, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_temp = QtWidgets.QLabel(parent=Dialog)
        self.label_temp.setObjectName("label_temp")
        self.gridLayout.addWidget(self.label_temp, 1, 0, 1, 1)
        self.doubleSpinBox_visc = DoubleSpinBoxNan(parent=Dialog)
        self.doubleSpinBox_visc.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_visc.setObjectName("doubleSpinBox_visc")
        self.gridLayout.addWidget(self.doubleSpinBox_visc, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.comboBox_lut = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_lut.setObjectName("comboBox_lut")
        self.gridLayout.addWidget(self.comboBox_lut, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.comboBox_medium.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Young\'s modulus computation"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>Here you can set the parameters for Young\'s modulus computation for all datasets loaded. This is the bulk-version of the corresponding options in the <span style=\" font-style:italic;\">Dataset  </span> tab in the <span style=\" font-style:italic;\">Analysis View</span>.</p></body></html>"))
        self.doubleSpinBox_temp.setSuffix(_translate("Dialog", "°C"))
        self.comboBox_medium.setItemText(0, _translate("Dialog", "CellCarrier"))
        self.comboBox_medium.setItemText(1, _translate("Dialog", "CellCarrier B"))
        self.comboBox_medium.setItemText(2, _translate("Dialog", "water"))
        self.comboBox_medium.setItemText(3, _translate("Dialog", "other"))
        self.comboBox_medium.setItemText(4, _translate("Dialog", "unknown"))
        self.label_6.setText(_translate("Dialog", "Medium"))
        self.comboBox_visc_model.setItemText(0, _translate("Dialog", "buyukurganci-2022"))
        self.comboBox_visc_model.setItemText(1, _translate("Dialog", "herold-2017"))
        self.comboBox_temp.setItemText(0, _translate("Dialog", "Configuration"))
        self.comboBox_temp.setItemText(1, _translate("Dialog", "Feature"))
        self.comboBox_temp.setItemText(2, _translate("Dialog", "Manual"))
        self.label_8.setText(_translate("Dialog", "Viscosity"))
        self.label_temp.setText(_translate("Dialog", "Temperature"))
        self.doubleSpinBox_visc.setSuffix(_translate("Dialog", " mPa·s"))
        self.label_2.setText(_translate("Dialog", "Look-up table"))
from dcscope.gui.widgets import DoubleSpinBoxNan
