# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './widgets/bulk_list.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_help_selection = QtWidgets.QLabel(parent=self.groupBox)
        self.label_help_selection.setOpenExternalLinks(True)
        self.label_help_selection.setObjectName("label_help_selection")
        self.horizontalLayout_2.addWidget(self.label_help_selection)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_none = QtWidgets.QToolButton(parent=self.groupBox)
        self.toolButton_none.setObjectName("toolButton_none")
        self.horizontalLayout_2.addWidget(self.toolButton_none)
        self.toolButton_all = QtWidgets.QToolButton(parent=self.groupBox)
        self.toolButton_all.setObjectName("toolButton_all")
        self.horizontalLayout_2.addWidget(self.toolButton_all)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "List content"))
        self.label_help_selection.setText(_translate("Form", "<a href=\"https://dcscope.readthedocs.io/en/stable/sec_qg_export_data.html#sec-qg-export-data-faq\">Why are not all selected?</a>"))
        self.toolButton_none.setText(_translate("Form", "select none"))
        self.toolButton_all.setText(_translate("Form", "select all"))
