# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './widgets/rangecontrol.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setText("")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.doubleSpinBox_min = SpinBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_min.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_min.setMaximumSize(QtCore.QSize(90, 16777215))
        self.doubleSpinBox_min.setDecimals(2)
        self.doubleSpinBox_min.setMaximum(100.0)
        self.doubleSpinBox_min.setObjectName("doubleSpinBox_min")
        self.horizontalLayout.addWidget(self.doubleSpinBox_min)
        self.range_slider = QRangeSlider(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range_slider.sizePolicy().hasHeightForWidth())
        self.range_slider.setSizePolicy(sizePolicy)
        self.range_slider.setObjectName("range_slider")
        self.horizontalLayout.addWidget(self.range_slider)
        self.doubleSpinBox_max = SpinBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_max.setMaximumSize(QtCore.QSize(90, 16777215))
        self.doubleSpinBox_max.setMaximum(100.0)
        self.doubleSpinBox_max.setObjectName("doubleSpinBox_max")
        self.horizontalLayout.addWidget(self.doubleSpinBox_max)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Feature description"))
from dcscope.gui.widgets import QRangeSlider
from pyqtgraph import SpinBox
