# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './export/e2plot.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 254)
        icon = QtGui.QIcon.fromTheme("draw-watercolor")
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_plot = QtWidgets.QComboBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_plot.sizePolicy().hasHeightForWidth())
        self.comboBox_plot.setSizePolicy(sizePolicy)
        self.comboBox_plot.setObjectName("comboBox_plot")
        self.horizontalLayout_2.addWidget(self.comboBox_plot)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_fmt = QtWidgets.QComboBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fmt.sizePolicy().hasHeightForWidth())
        self.comboBox_fmt.setSizePolicy(sizePolicy)
        self.comboBox_fmt.setObjectName("comboBox_fmt")
        self.comboBox_fmt.addItem("")
        self.comboBox_fmt.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_fmt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget_png = QtWidgets.QWidget(parent=Dialog)
        self.widget_png.setObjectName("widget_png")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_png)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget_png)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.spinBox_dpi = QtWidgets.QSpinBox(parent=self.widget_png)
        self.spinBox_dpi.setMinimum(72)
        self.spinBox_dpi.setMaximum(5000)
        self.spinBox_dpi.setSingleStep(100)
        self.spinBox_dpi.setProperty("value", 300)
        self.spinBox_dpi.setObjectName("spinBox_dpi")
        self.verticalLayout_2.addWidget(self.spinBox_dpi)
        self.checkBox_aa = QtWidgets.QCheckBox(parent=self.widget_png)
        self.checkBox_aa.setChecked(True)
        self.checkBox_aa.setObjectName("checkBox_aa")
        self.verticalLayout_2.addWidget(self.checkBox_aa)
        self.verticalLayout.addWidget(self.widget_png)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Plot export"))
        self.label_3.setText(_translate("Dialog", "Plot"))
        self.label_2.setText(_translate("Dialog", "File format"))
        self.comboBox_fmt.setItemText(0, _translate("Dialog", "rendered image (*.png)"))
        self.comboBox_fmt.setItemText(1, _translate("Dialog", "vector graphics (*.svg)"))
        self.label.setText(_translate("Dialog", "PNG export options:"))
        self.spinBox_dpi.setSuffix(_translate("Dialog", " DPI"))
        self.checkBox_aa.setText(_translate("Dialog", "Antialiasing"))
