# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './compute/comp_stats.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(693, 446)
        icon = QtGui.QIcon.fromTheme("view-statistics")
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.widget_other = QtWidgets.QWidget(parent=Dialog)
        self.widget_other.setObjectName("widget_other")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_other)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_path = QtWidgets.QLineEdit(parent=self.widget_other)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_3.addWidget(self.lineEdit_path)
        self.pushButton_path = QtWidgets.QPushButton(parent=self.widget_other)
        self.pushButton_path.setObjectName("pushButton_path")
        self.horizontalLayout_3.addWidget(self.pushButton_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_other)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox_filter_ray = QtWidgets.QComboBox(parent=self.widget_other)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_filter_ray.sizePolicy().hasHeightForWidth())
        self.comboBox_filter_ray.setSizePolicy(sizePolicy)
        self.comboBox_filter_ray.setObjectName("comboBox_filter_ray")
        self.horizontalLayout_4.addWidget(self.comboBox_filter_ray)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.widget_other)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bulklist_features = BulkList(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bulklist_features.sizePolicy().hasHeightForWidth())
        self.bulklist_features.setSizePolicy(sizePolicy)
        self.bulklist_features.setObjectName("bulklist_features")
        self.horizontalLayout_2.addWidget(self.bulklist_features)
        self.bulklist_stats = BulkList(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bulklist_stats.sizePolicy().hasHeightForWidth())
        self.bulklist_stats.setSizePolicy(sizePolicy)
        self.bulklist_stats.setObjectName("bulklist_stats")
        self.horizontalLayout_2.addWidget(self.bulklist_stats)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Compute and export statistical data"))
        self.label.setText(_translate("Dialog", "Compute statistics for multiple datasets."))
        self.comboBox.setItemText(0, _translate("Dialog", "All datasets of the current session"))
        self.comboBox.setItemText(1, _translate("Dialog", "All datasets in a directory"))
        self.lineEdit_path.setPlaceholderText(_translate("Dialog", "PATH"))
        self.pushButton_path.setText(_translate("Dialog", "Browse"))
        self.label_2.setToolTip(_translate("Dialog", "All filters from this filter ray will be applied before computing statistics"))
        self.label_2.setText(_translate("Dialog", "Filter ray"))
from dcscope.gui.widgets.bulk_list import BulkList
