# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './matrix/block_matrix.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(310, 464)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_block = QtWidgets.QScrollArea(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_block.sizePolicy().hasHeightForWidth())
        self.scrollArea_block.setSizePolicy(sizePolicy)
        self.scrollArea_block.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea_block.setLineWidth(1)
        self.scrollArea_block.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_block.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_block.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea_block.setWidgetResizable(True)
        self.scrollArea_block.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_block.setObjectName("scrollArea_block")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 462))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolButton_new_filter = QtWidgets.QToolButton(parent=self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("view-filter")
        self.toolButton_new_filter.setIcon(icon)
        self.toolButton_new_filter.setObjectName("toolButton_new_filter")
        self.gridLayout_3.addWidget(self.toolButton_new_filter, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.plot_matrix = PlotMatrix(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_matrix.sizePolicy().hasHeightForWidth())
        self.plot_matrix.setSizePolicy(sizePolicy)
        self.plot_matrix.setMinimumSize(QtCore.QSize(91, 67))
        self.plot_matrix.setObjectName("plot_matrix")
        self.gridLayout_3.addWidget(self.plot_matrix, 0, 3, 1, 1)
        self.toolButton_new_plot = QtWidgets.QToolButton(parent=self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("draw-watercolor")
        self.toolButton_new_plot.setIcon(icon)
        self.toolButton_new_plot.setObjectName("toolButton_new_plot")
        self.gridLayout_3.addWidget(self.toolButton_new_plot, 0, 4, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 5, 1, 1)
        self.data_matrix = DataMatrix(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_matrix.sizePolicy().hasHeightForWidth())
        self.data_matrix.setSizePolicy(sizePolicy)
        self.data_matrix.setMinimumSize(QtCore.QSize(67, 99))
        self.data_matrix.setObjectName("data_matrix")
        self.gridLayout_3.addWidget(self.data_matrix, 0, 0, 2, 2, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        self.toolButton_load_dataset = QtWidgets.QToolButton(parent=self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("office-chart-ring")
        self.toolButton_load_dataset.setIcon(icon)
        self.toolButton_load_dataset.setAutoRaise(False)
        self.toolButton_load_dataset.setObjectName("toolButton_load_dataset")
        self.gridLayout_3.addWidget(self.toolButton_load_dataset, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.gridLayout_3.setRowStretch(3, 1)
        self.scrollArea_block.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea_block)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton_new_filter.setToolTip(_translate("Form", "Add a new filter"))
        self.toolButton_new_filter.setText(_translate("Form", "+"))
        self.toolButton_new_plot.setToolTip(_translate("Form", "Add a new plot"))
        self.toolButton_new_plot.setText(_translate("Form", "+"))
        self.toolButton_load_dataset.setToolTip(_translate("Form", "Import a dataset"))
        self.toolButton_load_dataset.setText(_translate("Form", "+"))
from dcscope.gui.matrix.data_matrix import DataMatrix
from dcscope.gui.matrix.plot_matrix import PlotMatrix
