# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './analysis/ana_basins.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(701, 538)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget_dataset = QtWidgets.QListWidget(parent=Form)
        self.listWidget_dataset.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget_dataset.setProperty("showDropIndicator", False)
        self.listWidget_dataset.setAlternatingRowColors(True)
        self.listWidget_dataset.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.listWidget_dataset.setObjectName("listWidget_dataset")
        self.verticalLayout_2.addWidget(self.listWidget_dataset)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.treeWidget_basin_name = QtWidgets.QTreeWidget(parent=Form)
        self.treeWidget_basin_name.setProperty("showDropIndicator", False)
        self.treeWidget_basin_name.setAlternatingRowColors(True)
        self.treeWidget_basin_name.setAutoExpandDelay(0)
        self.treeWidget_basin_name.setUniformRowHeights(True)
        self.treeWidget_basin_name.setHeaderHidden(True)
        self.treeWidget_basin_name.setObjectName("treeWidget_basin_name")
        self.treeWidget_basin_name.headerItem().setText(0, "1")
        self.verticalLayout_3.addWidget(self.treeWidget_basin_name)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_id = QtWidgets.QLabel(parent=Form)
        self.label_id.setText("")
        self.label_id.setObjectName("label_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_id)
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.textEdit_def = QtWidgets.QTextEdit(parent=Form)
        self.textEdit_def.setReadOnly(True)
        self.textEdit_def.setObjectName("textEdit_def")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_def)
        self.label_status = QtWidgets.QLabel(parent=Form)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_status)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Dataset"))
        self.label_2.setText(_translate("Form", "Basins"))
        self.label_3.setText(_translate("Form", "Basin"))
        self.label_6.setText(_translate("Form", "Status"))
        self.label_5.setText(_translate("Form", "Definition"))
