# flake8: noqa
# This file was auto-generated with DCscope/ui/run_uic.sh.
# Form implementation generated from reading ui file './analysis/ana_meta.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 532)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_slots = QtWidgets.QComboBox(parent=Form)
        self.comboBox_slots.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox_slots.setObjectName("comboBox_slots")
        self.horizontalLayout.addWidget(self.comboBox_slots)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 680, 482))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_imaging = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_imaging.setObjectName("groupBox_imaging")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_imaging)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2.addWidget(self.groupBox_imaging, 4, 0, 1, 1)
        self.groupBox_setup = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_setup.setObjectName("groupBox_setup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_setup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addWidget(self.groupBox_setup, 3, 0, 1, 1)
        self.groupBox_online_filter = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_online_filter.setCheckable(False)
        self.groupBox_online_filter.setObjectName("groupBox_online_filter")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_online_filter)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2.addWidget(self.groupBox_online_filter, 7, 0, 1, 1)
        self.groupBox_experiment = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_experiment.setObjectName("groupBox_experiment")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_experiment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addWidget(self.groupBox_experiment, 0, 0, 1, 1)
        self.groupBox_user = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_user.setObjectName("groupBox_user")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_user)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_2.addWidget(self.groupBox_user, 2, 0, 1, 1)
        self.groupBox_fluorescence = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_fluorescence.setObjectName("groupBox_fluorescence")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_fluorescence)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2.addWidget(self.groupBox_fluorescence, 5, 0, 1, 1)
        self.groupBox_online_contour = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_online_contour.setObjectName("groupBox_online_contour")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_online_contour)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2.addWidget(self.groupBox_online_contour, 8, 0, 1, 1)
        self.groupBox_pipeline = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_pipeline.setObjectName("groupBox_pipeline")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_pipeline)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2.addWidget(self.groupBox_pipeline, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Dataset"))
        self.groupBox_imaging.setTitle(_translate("Form", "Imaging"))
        self.groupBox_setup.setTitle(_translate("Form", "Setup"))
        self.groupBox_online_filter.setTitle(_translate("Form", "Online Filter"))
        self.groupBox_experiment.setTitle(_translate("Form", "Experiment"))
        self.groupBox_user.setTitle(_translate("Form", "User"))
        self.groupBox_fluorescence.setTitle(_translate("Form", "Fluorescence"))
        self.groupBox_online_contour.setTitle(_translate("Form", "Online Contour"))
        self.groupBox_pipeline.setTitle(_translate("Form", "Pipeline"))
